# Generated by Django 6.0.5 on 2026-05-27 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Legal name of the organization', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly label for this feed', max_length=255)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement CSV'), ('UTILITY_ELECTRICITY', 'Utility Electricity Portal CSV'), ('CORP_TRAVEL', 'Corporate Travel JSON')], help_text='Expected format / adapter to use during validation', max_length=50)),
                ('expected_schema', models.JSONField(blank=True, default=dict, help_text='JSON mapping rules for parsing fields (e.g. source to destination fields)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Tenant that owns this configured data source', on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.organization')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
