# Generated by Django 6.0.5 on 2026-05-27 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_uuid_backup', models.UUIDField(blank=True, help_text='Immutable copy of the record ID to preserve history if record is deleted', null=True)),
                ('action', models.CharField(help_text='Type of action performed (e.g. RECORD_UPDATE, STATUS_CHANGE, AUDIT_LOCK)', max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dictionary containing before/after states of changed fields')),
                ('reason', models.TextField(blank=True, help_text='Analyst-provided comment explaining this manual edit or status change', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who executed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Tenant context of this audit log', on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='core.organization')),
                ('record', models.ForeignKey(blank=True, help_text='Associated emission record transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ingestion.emissionrecord')),
            ],
            options={
                'verbose_name': 'Audit Trail Log',
                'verbose_name_plural': 'Audit Trail Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
