# Generated by Django 6.0.5 on 2026-05-27 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original file name uploaded', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('PROCESSING', 'Processing Ingestion'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed Ingestion')], default='PENDING', max_length=50)),
                ('total_rows', models.IntegerField(default=0, help_text='Total rows in source file')),
                ('failed_rows', models.IntegerField(default=0, help_text='Rows failed during validation/parsing')),
                ('error_message', models.TextField(blank=True, help_text='Reason for system parsing error if batch fails', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(help_text='Configured data source template used to parse the file', on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='core.datasource')),
                ('organization', models.ForeignKey(help_text='Tenant that owns this batch', on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='core.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Analyst who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Batch',
                'verbose_name_plural': 'Upload Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField(help_text='1-indexed row index of raw source file')),
                ('raw_data_payload', models.JSONField(help_text='Exact raw unparsed input row dictionary')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Ingested'), ('SUSPICIOUS', 'Suspicious (Needs Review)'), ('VALIDATED', 'Validated (Ready for Approval)'), ('APPROVED', 'Approved & Audit Locked')], default='DRAFT', max_length=50)),
                ('is_suspicious', models.BooleanField(default=False, help_text='True if row values fall outside normal baseline ranges')),
                ('validation_errors', models.JSONField(blank=True, default=dict, help_text='Dictionary of validation errors or warnings found during ingestion')),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=6, help_text='Converted value in the target base unit', max_digits=20, null=True)),
                ('normalized_unit', models.CharField(blank=True, help_text='Standardized unit (e.g. kWh, Liters, Miles)', max_length=50, null=True)),
                ('scope_category', models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect Electricity)'), ('SCOPE_3', 'Scope 3 (Other Indirect / Travel)')], help_text='ESG greenhouse gas emissions scope definition', max_length=10, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.organization')),
                ('batch', models.ForeignKey(help_text='Source ingestion batch file context', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.uploadbatch')),
            ],
            options={
                'verbose_name': 'Emission Record',
                'verbose_name_plural': 'Emission Records',
                'ordering': ['batch', 'row_index'],
                'unique_together': {('batch', 'row_index')},
            },
        ),
    ]
