# Generated by Django 6.0.5 on 2026-05-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='scope_category',
            field=models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect Electricity)'), ('SCOPE_3', 'Scope 3 (Other Indirect / Travel)')], help_text='ESG greenhouse gas emissions scope definition', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft Ingested'), ('FAILED', 'Failed Validation (Excluded from Calculations)'), ('SUSPICIOUS', 'Suspicious (Needs Review)'), ('VALIDATED', 'Validated (Ready for Approval)'), ('APPROVED', 'Approved & Audit Locked')], default='DRAFT', max_length=50),
        ),
    ]
